### ISSUE TITLE
1000's of errors daily

### ISSUE THREAD

**Issue by preachur** [nopSolutions/avalara-plugin-for-nopcommerce#9]
For some reason, we are getting approximately 60,000 errors per day from this module every time any search engines index the site:

Avalara tax provider error. InvalidAddress - The address value was incomplete.
Details: The address value ShipTo was incomplete.  You must provide either a valid line + region + country + postal code.

and

Avalara tax provider - No response from the service

No errors with regular traffic. However, we just had 56,000+ of these errors in less than 24 hours, and it is ongoing. (Another 57,000 in less than 24 hours after this was posted in the support forums.)

**Comment by preachur** [comment]
![ava1](https://user-images.githubusercontent.com/40637964/42001567-fa8ec140-7a29-11e8-905e-6bf793e9c69d.jpg)
![ava2](https://user-images.githubusercontent.com/40637964/42001570-fafa009a-7a29-11e8-9363-76d42385ea35.jpg)
![ava3](https://user-images.githubusercontent.com/40637964/42001571-fb26a69a-7a29-11e8-89e2-be40283aefda.jpg)
Here are some screenshots. This is just from the point in time when I cleared the log after I reported this issue this morning.

**Comment by rossiter10** [comment]
I'm seeing something similar. Specifically, my issue has to do with guests who haven't entered an address yet. I'm on 3.90, version 1.31 of plugin.

In `AvalaraTaxProvider` -> `GetTaxRate()`, there is a null check on `calculateTaxRequest.Address`, but the `Address` is not null, just almost all the properties of the object are, like Address, City, etc... so the request fails. 

I ended up changing the setting with key `taxsettings.logerrors` to just turn off the logging since I didn't care in my case.

**Comment by RomanovM** [comment]
Just set default tax address to eliminate such errors http://admin-demo.nopcommerce.com/Admin/Setting/Tax. Default address is used for tax calculation due to missing addresses of search engine system customer.
